ALTER TABLE items ADD COLUMN lent_to    VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE items ADD COLUMN lent_at    DATE         NULL DEFAULT NULL;
ALTER TABLE items ADD COLUMN read_up_to INT          NULL DEFAULT NULL;
